"""add idempotency key to transactions

Revision ID: b79d18ed3797
Revises: d11f02bd69d8
Create Date: 2026-06-11 01:18:13.331903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79d18ed3797'
down_revision: Union[str, Sequence[str], None] = 'd11f02bd69d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'transactions', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    op.drop_column('transactions', 'idempotency_key')
    # ### end Alembic commands ###
